name: Caller-Workflow

on: 
  workflow_call:
    inputs:
      environment:
        description: Env name
        required: true
        type: string
jobs:
  deploy-and-display:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: Deploy job
        run: echo "Deploying the current Job" 
    
