name: Calling Workflow

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    uses: ChanduDeepak/sample-repo/.github/workflows/caller-workflow.yml@main
    with: 
      environment: "staging"
      
        
