name: Calling Workflow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    uses: ChanduDeepak/sample-repo/.github/workflows/caller-workflow.yml@main
    with: 
      environment: "staging"
      
        
