name: First Workflow
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo Hello, world!
      - name: Multi-line Commands
        run: |
          node -v
          npm -v

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View Software version
        run: sw_vers
  
  parallel-job-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Just sample step
        run: echo "I'm ubunutu, hi!"
      
  parallel-job-windows:
    runs-on: windows-latest
    steps:
      - name: It's Windows job
        run: echo "I'm Windows, hi!"

  dependent-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo a string
        run: Write-Output "Windows string"
      - name: Error step
        run: IntentionalErrorstep-that fails
